name: kube.lab CI pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kube.lab repo
        uses: actions/checkout@v5

      - name: Create .env file
        run:
          echo "POSTGRES_USER=postgres" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB=mydb" >> .env
          echo "LDAP_ADMIN_PASSWORD=${{ secrets.LDAP_ADMIN_PASSWORD }}" >> env.
          echo "LDAP_PASSWORD=${{ secrets.LDAP_PASSWORD }}" >> env.

      - name: Build containers
        run: docker compose build

      - name: Start containers
        run: docker compose up -d

      - name: Wait for API
        run: |
          sleep 20
          curl -v http://localhost/api | exit 1

      - name: Test API endpoint (LDAP)
        run: |
          curl --fail http://localhost/api/users || exit 1

      - name: Test API endpoint (POSTGRES)
        run: |
          curl --fail http://localhost/api/postgres_test || exit 1

      - name: Stop containers
        run: docker compose down


